
import { Review, ContentType, UserList, Business } from './types';

export const USERS = {
  u1: {
    id: 'u1',
    username: 'foodie_jane',
    displayName: 'Jane Doe',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80',
    bio: 'Chasing the best flavors in Athens 🇬🇷 | Professional Taster',
    followers: 1205,
    following: 450,
    postsCount: 142,
    isVerified: true,
    socialLinks: {
      instagram: 'foodie_jane',
      tiktok: 'foodie_jane',
      twitter: 'jane_eats'
    }
  },
  u2: {
    id: 'u2',
    username: 'burger_boss',
    displayName: 'Alex Smith',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
    isVerified: true,
    bio: 'If it has a bun, I am there. 🍔',
    socialLinks: { instagram: 'burger_boss_official' }
  },
  u3: { 
    id: 'u3', 
    username: 'coffee_alex', 
    displayName: 'Alex P.', 
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop', 
    isVerified: true,
    socialLinks: { instagram: 'alex_brews' }
  },
  u4: { 
    id: 'u4', 
    username: 'sushi_queen', 
    displayName: 'Elena S.', 
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop', 
    isVerified: true,
    socialLinks: { tiktok: 'elena_sushi' }
  },
  u5: { 
    id: 'u5', 
    username: 'athens_local', 
    displayName: 'Nikos G.', 
    avatarUrl: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=200&h=200&fit=crop',
    bio: 'Showing you the hidden alleys of my city.'
  }
};

export const BUSINESSES: Record<string, Business> = {
  b1: {
    id: 'b1',
    name: 'Plaka Taverna',
    username: 'plaka_taverna',
    displayName: 'Plaka Taverna',
    category: 'Greek Restaurant',
    location: 'Adrianou 12, Plaka',
    avatarUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=200&h=200&fit=crop',
    coverImageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
    isVerified: true,
    rating: 4.8,
    reviewCount: 1240,
    priceLevel: '$$$',
    isOpen: true,
    latLng: [37.9725, 23.7297],
    distance: '200m',
    walkingTime: '3 min',
    ratingBreakdown: { 5: 800, 4: 300, 3: 100, 2: 30, 1: 10 }
  },
  b2: {
    id: 'b2',
    name: 'Gyro King',
    username: 'gyro_king',
    displayName: 'Gyro King',
    category: 'Street Food',
    location: 'Monastiraki Sq 5',
    avatarUrl: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=200&h=200&fit=crop',
    coverImageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80',
    isVerified: true,
    rating: 4.5,
    reviewCount: 3400,
    priceLevel: '$',
    isOpen: true,
    latLng: [37.9765, 23.7257],
    distance: '100m',
    walkingTime: '1 min',
    ratingBreakdown: { 5: 2000, 4: 1000, 3: 200, 2: 150, 1: 50 }
  },
  b3: {
    id: 'b3',
    name: 'Little Tree Books',
    username: 'littletree_ath',
    displayName: 'Little Tree',
    category: 'Coffee Shop',
    location: 'Kavalloti 2, Makrygianni',
    avatarUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=200&h=200&fit=crop',
    coverImageUrl: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800&q=80',
    isVerified: false,
    rating: 4.2,
    reviewCount: 450,
    priceLevel: '$$',
    isOpen: true,
    latLng: [37.9675, 23.7237],
    distance: '350m',
    walkingTime: '5 min'
  },
  b4: {
    id: 'b4',
    name: 'Peinirli Ionias',
    username: 'peinirli_ionias',
    displayName: 'Peinirli Ionias',
    category: 'Bakery',
    location: 'Panormou 11',
    avatarUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=200&h=200&fit=crop',
    coverImageUrl: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=800&q=80',
    isVerified: true,
    rating: 4.7,
    reviewCount: 5200,
    priceLevel: '$',
    isOpen: true,
    latLng: [37.9925, 23.7657],
    distance: '2.5km',
    walkingTime: '30 min'
  },
  b5: {
    id: 'b5',
    name: 'Sushi Zen',
    username: 'sushi_zen',
    displayName: 'Sushi Zen',
    category: 'Japanese',
    location: 'Syntagma Sq 3',
    avatarUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=200&h=200&fit=crop',
    coverImageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80',
    isVerified: true,
    rating: 4.9,
    reviewCount: 890,
    priceLevel: '$$$$',
    isOpen: true,
    latLng: [37.9755, 23.7347],
    distance: '800m',
    walkingTime: '10 min'
  }
};

export const MOCK_FEED: Review[] = [
  {
    id: 'v1-muckbang',
    type: ContentType.USER_REVIEW,
    mediaType: 'video',
    author: USERS.u2,
    businessId: 'b2',
    businessName: 'Gyro King',
    rating: 5.0,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-taking-a-bite-of-a-delicious-burger-32890-large.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=800&q=80',
    text: 'ULTIMATE MUCKBANG! 🌯 Honestly, the garlic sauce here is life-changing. #muckbang #foodie #athens #video',
    timestamp: '2m ago',
    agreeCount: 12400,
    disagreeCount: 15,
    commentCount: 890,
    tags: ['muckbang', 'video', 'gyro', 'streetfood']
  },
  {
    id: 'bp1-plaka',
    type: ContentType.BUSINESS_POST,
    mediaType: 'video',
    author: BUSINESSES.b1,
    businessId: 'b1',
    businessName: 'Plaka Taverna',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-chef-flaming-a-dish-in-a-pan-33100-large.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
    text: 'Our signature Saganaki is flaming hot tonight! 🔥 Come try the tradition. #plaka #greekfood #official',
    timestamp: '1h ago',
    agreeCount: 4200,
    disagreeCount: 0,
    commentCount: 120,
    tags: ['tradition', 'official', 'greek']
  },
  {
    id: 'v2-pov',
    type: ContentType.USER_REVIEW,
    mediaType: 'video',
    author: USERS.u4,
    businessId: 'b5',
    businessName: 'Sushi Zen',
    rating: 4.9,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hand-dipping-a-piece-of-sushi-in-soy-sauce-41618-large.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80',
    text: 'POV: You are eating the best Otoro in the city. 🍣✨ #POV #sushi #luxury #video',
    timestamp: '15m ago',
    agreeCount: 5600,
    disagreeCount: 2,
    commentCount: 145,
    tags: ['POV', 'video', 'sushi', 'zen']
  },
  {
    id: 'bp2-gyro',
    type: ContentType.BUSINESS_POST,
    mediaType: 'video',
    author: BUSINESSES.b2,
    businessId: 'b2',
    businessName: 'Gyro King',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-fast-food-worker-wrapping-a-burrito-32616-large.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800&q=80',
    text: 'Behind the scenes at the shop! 🌯 Quality ingredients, every single time. 👑 #gyroking #fresh #official',
    timestamp: '3h ago',
    agreeCount: 8900,
    disagreeCount: 5,
    commentCount: 450,
    tags: ['behindthescenes', 'official', 'streetfood']
  },
  {
    id: 'v3-muckbang',
    type: ContentType.USER_REVIEW,
    mediaType: 'video',
    author: USERS.u1,
    businessId: 'b1',
    businessName: 'Plaka Taverna',
    rating: 4.8,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-pouring-red-wine-into-a-glass-in-slow-motion-42633-large.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
    text: 'A quick tour of the vibes at Plaka Taverna. 🍷 Perfect for date nights! #video #vibes #winereview',
    timestamp: '45m ago',
    agreeCount: 3200,
    disagreeCount: 0,
    commentCount: 64,
    tags: ['video', 'plaka', 'wine', 'datenight']
  },
  {
    id: 'bp3-sushi',
    type: ContentType.BUSINESS_POST,
    mediaType: 'image',
    author: BUSINESSES.b5,
    businessId: 'b5',
    businessName: 'Sushi Zen',
    imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80',
    text: 'Introducing our Autumn Omakase Menu. 🍂 Reservation links in bio. #sushizen #luxury #newmenu',
    timestamp: '5h ago',
    agreeCount: 1500,
    disagreeCount: 0,
    commentCount: 45,
    tags: ['newmenu', 'luxury', 'sushi']
  },
  {
    id: 'v4-pov',
    type: ContentType.USER_REVIEW,
    mediaType: 'video',
    author: USERS.u5,
    businessId: 'b4',
    businessName: 'Peinirli Ionias',
    rating: 5.0,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-fresh-bread-coming-out-of-the-oven-41589-large.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80',
    text: 'The best cheese pull I have ever filmed! 🧀 Check this out. #cheese #muckbang #video',
    timestamp: '1h ago',
    agreeCount: 8900,
    disagreeCount: 1,
    commentCount: 420,
    tags: ['video', 'muckbang', 'bakery', 'cheese']
  },
  {
    id: 'v5-review',
    type: ContentType.USER_REVIEW,
    mediaType: 'video',
    author: USERS.u3,
    businessId: 'b3',
    businessName: 'Little Tree Books',
    rating: 4.2,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-putting-sugar-into-a-cup-of-coffee-41617-large.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    text: 'Quiet morning coffee at Little Tree. ☕️📚 Best hidden gem. #coffee #video #POV',
    timestamp: '2h ago',
    agreeCount: 1200,
    disagreeCount: 5,
    commentCount: 32,
    tags: ['video', 'coffee', 'books', 'POV']
  },
  {
    id: 'img1',
    type: ContentType.USER_REVIEW,
    mediaType: 'image',
    author: USERS.u2,
    businessId: 'b2',
    businessName: 'Gyro King',
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80',
    text: 'Absolute classic. Never disappoints.',
    timestamp: '3h ago',
    agreeCount: 890,
    disagreeCount: 10,
    commentCount: 45,
    tags: ['athens', 'streetfood']
  }
];

export const ALL_POSTS: Review[] = [...MOCK_FEED];
export const MOCK_LISTS: UserList[] = [
  { id: 'l1', authorId: 'u1', title: '🏺 Best Views of Acropolis', coverUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=80', itemCount: 12, isPrivate: false },
  { id: 'l2', authorId: 'u1', title: '🍣 Sushi Gems', coverUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80', itemCount: 5, isPrivate: false },
  { id: 'l3', authorId: 'u2', title: '🍔 Burger Pilgrimage', coverUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80', itemCount: 15, isPrivate: false }
];
